name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code of ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Clone Scripts repository
        uses: actions/checkout@main
        with:
          repository: andresnboza/reloadAppScripts
          path: ./reloadAppScripts
      - name: List files in scripts folder
        run: |
          cp ReadmeAppService1.md reloadAppScripts/ReadmeAppService1.md && cd reloadAppScripts
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython
          pip install bson
          pip install pymongo
      - name: Execute the save
        run: |
          cd reloadAppScripts
          python3 save2.py ${{ secrets.FILE_NAME }} ${{ secrets.MONGO_URI }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
